**Tugas Minggu Ke-5**

# **5.16 List 2 Dimensi**

---

List 2 dimensi adalah sebuah struktur data yang terdiri dari daftar elemen yang terorganisir dalam baris dan kolom 
(memiliki 2 indeks, yaitu indeks baris dan indeks kolom). Elemen di dalam list 2 dimensi biasanya memiliki tipe data yang sama.
List 2 dimensi umumnya menempatka sebuah list di dalam list. Penggambarannya seperti sebuah matriks. 

In [1]:
# Latihan 1 List 2 Dimensi

# Mendefinisikan variabel
angka_03 = [
    [2,4,6,8],
    [1,3,5,7],
    [2,3,5],
    [1,1,3]
]
print(angka_03)

# Pada saat kita definisikan variabel dan isinya, kita buat urutan matriksnya berurut kebawah (vertikal)
# Namun, dapat dilihat outputnya akan menghasilkan urutan angka_03 secara mendatar (horizontal)
# Dapat dilihat bahwa panjang list sebagai elemen tidak harus sama

[[2, 4, 6, 8], [1, 3, 5, 7], [2, 3, 5], [1, 1, 3]]


In [2]:
# Latihan 2 List 2 Dimensi

# Mendefinisikan variabel
angka_03 = 
    [2,4,6,8],
    [1,3,5,7],
    [2,3,5],
    [1,1,3]

print(angka_03)

# Disini akan error karena tidak ada tanda kurung siku "[]" di awal dan akhir dari isi variabel angka_03
# Sehingga invalid syntax karena disebelah tanda "=" tidak terdefinisi nilai apapun untuk variabel

SyntaxError: ignored

In [3]:
# Latihan 3 List 2 Dimensi

# Mendefinisikan variabel
angka_03 = 2,4,6,8
          1,3,5,7
          2,3,5
          1,1,3

print(angka_03)

# Disini juga akan error karena tidak ada tand kurung siku "[]" di awal dan akhir elemen list 2 dimensi
# Tanda kurung siku "[]" pada list 2 dimensi digunakan untuk menunjukkan bahwa struktur data adalah sebuah array multidimensi
# Outputnya akan error karena ketika tidak menggunakan tanda kurung siku "[]" pada list 2 dimensi, 
# maka struktur datanya tidak dikenali sebagai array multidimensi, melainkan hanya sebagai objek biasa. 

IndentationError: ignored

In [4]:
# Latihan 4 List 2 Dimensi

# Mencetak elemen list 2 dimensi dari index tertentu
angka_03[3]

# Disini outputnya akan berupa elemen dalam urutan data ke-4, yaitu [1,1,3]
# Ingat kembali index! Bahwa jika dihitung dari depan maka dimulai dari 0

[1, 1, 3]

In [5]:
# Latihan 5 List 2 Dimensi

# Mencetak elemen list 2 dimensi dengan index tertentu
angka_03[-2]

# Disini outputnya akan berupa elemen dalam urutan data ke 2 dari belakang, karena indexnya bernilai negatif
# Ingat kembali! Pada index jika bernilai negatif artinya dihitung dari belakang dan dimulai dari -1
# Maka outputnya pastilah [2,3,5]

[2, 3, 5]

In [6]:
# Latihan 6 List 2 Dimensi

# Mencetak elemen list 2 dimensi dengan index tertentu
angka_03[0][2]

# [0] diatas menunjukkan pada list pertama dalam list "angka_03", maka artinya ada di [2,4,6,8]
# [2] diatas merujuk pada elemen ketiga dalam list
# Atau dapat disimpulkan jika ada perintah angka_03[a][b], maka [a] disana menyatakan baris dan [b] menyatakan kolom
# Artinya kita meminta elemen yang terletak di baris pertama dan kolom ketiga
# Karena baris pertama adalah [2,4,6,8] dan kolom ketiga pada baris itu adalah itu adalah 6, maka outputnya pasti 6

6

In [7]:
# Latihan 7 List 2 Dimensi

# Mengubah elemen list 2 dimensi di index tertentu
angka_03[0][3]=75            # Disini kita meminta untuk mengubah/mengganti baris pertama kolom ke empat dengan 4
print(angka_03[0][3])

angka_03
# Terlihat di output bahwa sebelumnya elemen di baris pertama kolom ke empat adalah 8, namun sekarang telah berubah menjadi 75

75


[[2, 4, 6, 75], [1, 3, 5, 7], [2, 3, 5], [1, 1, 3]]

In [8]:
# Latihan 8 List 2 Dimensi

# Mengubah elemen list 2 dimensi di index tertentu
angka_03[-2][2]=12         # Disini kita meminta untuk mengubah baris kedua terakhir dan kolom ketiganya dengan 5
print(angka_03[-1][2])

angka_03
# Terlihat di output bahwa sebelumnya elemen di baris kedua terakhir kolom ketiganya adalah 5, namun sekarang telah berubah menjadi 12

3


[[2, 4, 6, 75], [1, 3, 5, 7], [2, 3, 12], [1, 1, 3]]

In [9]:
# Latihan 9 List 2 Dimensi

# Mengubah elemen list 2 dimensi di index tertentu
angka_03[2][3]= 250            # Disini kita meminta untuk mengubah baris ketiga kolom ke empat dengan 4
print(angka_03[2][3])

angka_03

# Akan terjadi error karena index yang kita minta tidak berada di dalam range 
# Baris ketiga hanya sampai 3 kolom, sementara kita meminta untuk mengubah elemen di kolom ke empat

IndexError: ignored

# **5.17 Tuples**

---

Tuples adalah tipe data dalam Python yang mirip dengan List. Namun, tuples bersifat immutabel, yaitu tidak dapat diubah setelah dibuat.

In [10]:
# Latihan 1 Tuples
# Mendefinisikan sebuah variabel pada tuples
buah_03 = ("apel", "anggur", "ceri", "duku", "durian", "stroberi")

# Jika elemen dari tuples adalah sebuah karakter/kata maka harus digunakan tanda petik baik petik dua ataupun petik satu
# Karena jika tidak, maka tidak terdefinisikan
# Sebab Python menganggap bahwa karakter/kata yang ditulis tanpa tanda petik adalah keyword dari bahasa pemrograman

In [11]:
# Kita coba
buah_03 = (apel, anggur, ceri, duku, durian, stroberi)

# Benar hasilnya error

NameError: ignored

In [12]:
# Bandingkan dengan ini
angka_03 = (1,4,7,10,13,16)

# Jika elemennya berupa bilangan/angka, tidak diperlukan tanda petik karena Python sudah membacanya sebagai konstanta numerik

In [13]:
# Latihan 2 Tuples

# Mencetak elemen tuples dengan index tertentu
print(buah_03[3])         

# Disini kita meminta index[3] artinya kita meminta elemen yang terletak di urutan ke empat
# Ingat kembali urutan menghitung dalam index!

duku


In [14]:
# Latihan 3 Tuples

# Mencetak elemen tuples dengan index tertentu
print(buah_03[1:3])           
# Disini kita meminta untuk mencetak elemen yang terletak di urutan kedua sampai keempat
# Ingat kembali bahwa pada index jika ada perintah print(x[a:b]) maka elemen yang diminta ada di urutan a+1 dan (b+1)-1
# Secara singkatnya elemen terakhir dari interval index tidak ikut ditampilkan
# Pada perintah di atas kita meminta elemen di urutan kedua sampai urutan keempat
# namun outputnya hanya akan elemen urutan kedua sampai ketiga, yaitu "anggur" dan "ceri"

print("\n Bandingkan dengan output dibawah ini \n")

# Mencetak elemen tuples dengan index tertentu
print(buah_03[1:2])
# Disini kita meminta untuk mencetak elemen yang terletak di urutan kedua sampai ketiga
# Namun, yang akan menjadi output hanya elemen di urutan kedua saja karena ketiga tidak ikut ditampilkan
# Maka outputnya adalah "anggur" dan kosong

('anggur', 'ceri')

 Bandingkan dengan output dibawah ini 

('anggur',)


In [15]:
# Latihan 4 Tuples

for isi in buah_03[0:3]:
  print(isi)

# Kita meminta elemen di urutan pertama sampai keempat
# Namun outputnya hanya akan mencetak elemen urutan pertama sampai ketiga
# Dapat dilihat output disini berbeda dengan output di atas, disini outputnya berurut ke bawah (vertikal)

apel
anggur
ceri


In [16]:
# Latihan 5 Tuples

# Mencetak elemen dari tuples dengan index tertentu
buah_03[2]        # Disini kita meninta index[2] artinya elemen di urutan ketiga, maka outputnya pasti "ceri"
buah_03[-3]       # Disini kita meminta index[-3] artinya elemen ketiga terakhir, maka outputnya pasti "duku"

# Ingat! jika index dihitung dari depan maka urutan awalnya dimulai dari 0
# Jika dari belakang maka menggunakan bilangan negatif dimulai dari -1

# Hasilnya hanya output dari perintah buah_03[-3]
# Hal ini terjadi karena tidak ada perintah print, sehingga python menjalankan perintah terakhir yang diminta

'duku'

In [17]:
# Akan kita pisahkan
buah_03[2]

# Outputnya pasti adalah "ceri"

'ceri'

In [18]:
# Latihan 6 Tuples

# Mencetak elemen tuples dengan index tertentu
buah_03[6]

# Outputnya akan error karena kita meminta elemen di urutan ke 7, sementara data kita hanya sebanyak 6
# Index keluar dari range!

IndexError: ignored

In [19]:
# Latihan 7 Tuples

# Menambahkan suatu elemen di urutan paling belakang/akhir di tuples
buah_03.append("semangka")

# Terjadi error!
# Karena tuples adalah tipe data yang tidak dapat diubah ketika sudah dibuat

AttributeError: ignored

In [20]:
# Latihan 8 Tuples

# Menghapus suatu elemen dari tuples
buah_03.remove("anggur")

# Terjadi error!
# Karena tuples adalah tipe data yang tidak dapat diubah ketika sudah dibuat

AttributeError: ignored

In [21]:
# Latihan 9 Tuples

# Menghitung banyak suatu elemen tuple
buah_03.count("duku")

# Outputnya pasti 1 karena "duku" pada tuple hanya ada 1

1

In [22]:
# Latihan 10 Tuples

# Mencari letak atau posisi (index) suatu elemen tuples
buah_03.index("stroberi")     # Kita mencari index "stroberi" pada tuples, maka outputnya pasti 5, karena "stroberi" terletak di urutan ke enam

5

# **5.18 Dictionaries**

---

Dictionaries adlaah struktur data yang memungkinkan pengguna untuk menyimpan dan mengakses data dalam bentuk pasangan "key-value" (terikat satu sama lain)

In [23]:
# Latihan 1 Dictionaries

# Mendefinisikan sebuah variabel
data_orang_03 = {
    "nama_03"         : "Naftalia",
    "nim_03"          : "2208541003",
    "kelas_03"        : "A",
    "mata_kuliah_03"  : "Algoritma dan Struktur Data",
    "apakah_mahasiswa": True
}

In [24]:
# Latihan 1 Dictionaries

# Mendefinisikan sebuah variabel
data_orang_03 = 
    "nama_03"         : "Naftalia",
    "nim_03"          : "2208541003",
    "kelas_03"        : "A",
    "mata_kuliah_03"  : "Algoritma dan Struktur Data",
    "apakah_mahasiswa": True

# Mengapa error ya?
# Sama seperti list 2 dimensi
# Tanda kurung kurawal "{}" pada dictionaries digunakan untuk menunjukkan bahwa elemen didalamnya adalah key-value atau saling terikat
# Outputnya akan error ketika tidak menggunakan tanda kurung kurawal "{}" pada dictionaries
# Karena struktur datanya tidak dikenali sebagai key-value, melainkan hanya sebagai objek biasa
# Sehingga invalid syntax karena disebelah tanda "=" tidak terdefinisi nilai apapun untuk variabel

SyntaxError: ignored

In [25]:
# Mendefinisikan sebuah variabel
data_orang_03 = {
    "nama_03"         : "Naftalia"
    "nim_03"          : "2208541003"
    "kelas_03"        : "A"
    "mata_kuliah_03"  : "Algoritma dan Struktur Data"
    "apakah_mahasiswa": True
}

# Error lagi
# Ini terjadi karena tidak ada tanda koma "," yang memisahkan setiap pasangan key-value
# Padahal key-value harus dipisahkan agar program dapat membedakan antara satu pasnagan dengan yang lainnya
# Jika tidak ada koma, maka program menganggap semua elemen dalam dictionaries adalah satu kesatuan sehingga akan menghasilkan error

# Jadi jangan lupa untuk menggunakan tanda kurung kurawal "{}" dan tanda koma ","

SyntaxError: ignored

In [26]:
# Latihan 2 Dictionaries

# Mencetak value dari sebuah key
print(data_orang_03["nim_03"])    # Disini kita meminta untuk mencetak nilai dari nim_03

2208541003


In [29]:
# Latihan 3 Dictionaries

# Mencetak value dari sebuah key
print(data_orang_03["NIM_03"])

# Outputnya akan error karena Python sensitif terhadap penggunaan huruf kapital dan huruf kecil
# Pada dictionaries tidak ada "NIM_03" yang ada ialah "nim_03"    (perhatikan penggunaan huruf kapitaldan huruf kecil)

KeyError: ignored

In [30]:
# Latihan 4 Dictionaries

# Menggunakan dictionaries.get(x) untuk mnencetak nilai(value) dari sebuah key

print(data_orang_03.get("Nama_03"))
# Disini "Nama" tidak ada dalam dictionaries, maka hasilnya akan "None"

print(data_orang_03.get("nama_03"))
# "nama_03" akan terdefinisi, karena berada di dictionaries. Maka outputnya pasti "Naftalia" karena nilai dari "nama_03" adalah "Naftalia"


# Ingat kesensitifan Python terhadap huruf kapital dan huruf kecil

None
Naftalia


In [31]:
# Latihan 5 Dictionaries

# Mencetak nilai(value) dari suatu key pada dictionaries
print(data_orang_03.get("kelas_03"))

A


In [32]:
# Latihan 6 Dictionaries

# Mencetak nilai(value) dari suatu key pada dictionaries
print(data_orang_03.get("kelas_03", "C"))

# Tidak akan terjadi perubahan apa-apa, karena perintah print(dictionaries.get(x)) hanya mencetak nilai (value) dari "kelas_03" atau "C"
# "C" bukanlah key pada dictionaries, sehingga nilai(value) dari "C" tidak ada, maka yang dicetak hanyalah value dari "kelas_03"

A


In [33]:
# Latihan 7 Dictionaries

# Mencetak seluruh dictionaries
print(data_orang_03)

{'nama_03': 'Naftalia', 'nim_03': '2208541003', 'kelas_03': 'A', 'mata_kuliah_03': 'Algoritma dan Struktur Data', 'apakah_mahasiswa': True}


In [34]:
# Latihan 8 Dictionaries

# Mencetak nilai(value) dari suatu key pada dictionaries
print(data_orang_03["nama_03"])
print(data_orang_03["nim_03"])

# Ketika memiliki output, outputnya memang akan sama dengan output dari 
# perintah print(data_orang_03.get("nama_03)) dan print(data_orang_03.get("nim_03"))

print("\n")

print(data_orang_03["Nama_03"])
# Namun, ketika "Nama_03" tidak berada dalam dictionaries hasilnya bukanlah "None" seperti pada perintah print(data_orang_03.get("Nama_03))
# Melainkan outputnya error

Naftalia
2208541003




KeyError: ignored

In [35]:
# Latihan 9 Dictionaries

# Menambahkan key dalam dictionaries
data_orang_03["email_03"] = "naftaliasophiana@gmail.com"

In [36]:
# Latihan 10 Dictionaries 

# Mencetak nilai(value) dari key pada dictionary
print(data_orang_03["email_03"])

naftaliasophiana@gmail.com


In [37]:
# Latihan 11 Dictionaries

# Mencetak dictionaries
print(data_orang_03)

# Outputnya akan menghasilkan seluruh key-value pada dictionaries
# Dapat dilihat pada output bahwa elemen dictionariesnya bertambah, yaitu ada "email_03" : "naftaliasophiana@gmail.com"
# Ini berarti Python akan selalu menyimpan output terakhir dan mengingatnya

{'nama_03': 'Naftalia', 'nim_03': '2208541003', 'kelas_03': 'A', 'mata_kuliah_03': 'Algoritma dan Struktur Data', 'apakah_mahasiswa': True, 'email_03': 'naftaliasophiana@gmail.com'}


# **5.19 Fungsi dalam Python**

---

Fungsi dalam Python adalah blok kode yang dirancang untuk menjalankan tugas tertentu. Kita sudah mempelajari beberapa fungsi dalam Python, antaralain input, print, len, range. 

In [38]:
# Latihan 1 Fungsi dalam Python

# Inisialiasi fungsi "waktu_tempuh_03" yang membutuhkan jarak_03 dan kecepatan_03
def waktu_tempuh_03(jarak_03, kecepatan_03):
  # Di bawah ini adalah rumus waktu jika diketahui jarak dan kecepatannya
  waktu_03 = jarak_03/kecepatan_03
  return waktu_03
  # Digunakan operator "return" untuk memanggil kembali variabel operasi fungsinya

# Kita masukkan nilai jarak dan kecepatan
# dengan variabel y untuk mendefinisikan waktu_tempuh_03 
y = waktu_tempuh_03(75,80)

print("Jarak dari A ke B sebesar 75 km ditempuh menggunakan mobil dengan kecepatan 80 km/jam")
print("Maka, mobil tersebut menempuh perjalanan dari A ke B selama", y , "jam")


Jarak dari A ke B sebesar 75 km ditempuh menggunakan mobil dengan kecepatan 80 km/jam
Maka, mobil tersebut menempuh perjalanan dari A ke B selama 0.9375 jam


In [39]:
# Latihan 2 Fungsi dalam Python

# Inisialisasi fungsi luas_persegi_03 yang membutuhkan sisi
def luas_persegi_03(sisi):
  # Di bawah ini adalah rumus luas persegi
  luas_03 = sisi**2
  return luas_03
  # Digunakan operator "return" untuk memanggil kembali variabel operasi fungsinya

# Kita masukkan nilai sisi
# dengan variabel a untuk mendefinisikan luas_persegi_03
a = luas_persegi_03(3)

print("Jika suatu persegi memiliki sisi sepanjang 3 cm, maka luas persegi tersebut adalah", a , "cm")

# Inisialisasi fungsi luas_trapesium_03 yang membutuhkan sisi sejajar atas, sisi sejajar bawah, dan tinggi
def luas_trapesium_03(sisi_sejajar_atas,sisi_sejajar_bawah,tinggi):
  # Di bawah ini adalah rumus luas trapesium
  luas_03 = (1/2)*(sisi_sejajar_atas + sisi_sejajar_bawah)*tinggi
  return luas_03
  # Digunakan operator "return" untuk memanggil kembali variabel operasi fungsinya

# Kita masukkan nilai sisi_sejajar_atas, sisi_sejajar_bawah, dan tinggi
# dengan variabel b untuk mendefinisikan luas_trapesium_03
b = luas_trapesium_03(4,7,3)

print("\nJika suatu trapesium memiliki sisi sejajar atas 4 cm, sisi sejajar bawah 7 cm, dan tinggi 3 cm, maka luas trapesium tersebut adalah", b , "cm")

Jika suatu persegi memiliki sisi sepanjang 3 cm, maka luas persegi tersebut adalah 9 cm

Jika suatu trapesium memiliki sisi sejajar atas 4 cm, sisi sejajar bawah 7 cm, dan tinggi 3 cm, maka luas trapesium tersebut adalah 16.5 cm


# **5.20 Numpy**


---

Numpy adalah library pada Python yang unggul dalam perhitungan menggunakan vektor dan matriks dalam berbagai dimensi.

**5.20.1 Perintah dasar pada Numpy**

In [40]:
# Latihan 1 Perintah dasar Numpy

# Inisialisasi numpy sebagai np
import numpy as np

# Mendefinisikan variabel dengan fungsi array pada numpy
A = np.array([2,3,4,5,6])
# Hasil variabel A
print(A)

print("\n")

# Mendefinisikan variabel dengan fungsi array pada numpy
B = np.array([[1,2,3,4],[1,2,3,4]])
# Hasil dari variabel B
print(B)

[2 3 4 5 6]


[[1 2 3 4]
 [1 2 3 4]]


In [41]:
A.ndim
# Disini dilihat jumlah dimensi dari A
# Dari output bisa kita ketahui jika jumlah dimensi dihitung dari jumlah pasangan kurung siku

1

In [42]:
B.ndim
# Disini dilihat jumlah dimensi dari B
# Dari output bisa kita ketahui jika jumlah dimensi dihitung dari jumlah pasangan kurung siku

2

In [43]:
# x.shape digunakan untuk mengembalikan tuple yang menunjukkan ukuran atau dimensi dari suatu array
# x disini adalah variabel yang telah didefinisikan
# Jika "x" adalah array satu dimensi dengan "n" elemen, maka x.shape akan mengembalikan nilai "(n,)"
# Jika "x" adalah array dua dimensi dengan "m" baris dan "n" kolom, maka x.shape akan mengembalikan nilai "(m,n)" dan seterusnya

A.shape
# A disini adalah array satu dimensi, maka outputnya akan "(n,)" dimana n adalah jumlah elemen A

(5,)

In [44]:
B.shape
# B disini adalah array dua dimensi, maka outputnya akan "(m,n)" dimana "m" adalah jumlah baris dan "n" jumlah kolom

(2, 4)

**5.20.2 Memanggil anggota, kolom dan baris dengan Numpy**

In [45]:
# Latihan 1 memanggil anggota, kolom, dan baris dengan numpy

# Mendefinisikan variabel dengan fungsi array pada numpy
R = np.array([[2,4,5,1],[1,3,7,6],[6,8,5,3],[12,4,5,3]])
print(R)
# Hasilnya akan berupa matriks

[[ 2  4  5  1]
 [ 1  3  7  6]
 [ 6  8  5  3]
 [12  4  5  3]]


In [46]:
# Latihan 2 memanggil anggota, kolom, dan baris dengan numpy

# Memilih elemen atau subarray dari array R dengan menggunakan index
# Ingat kembali cara menghitung index! dimulai dari 0 untuk urutan pertama dari depan

a = R[0,3]
print("Elemen pada baris ke-1 dan kolom ke-4 di R adalah", a)
# Disini akan diambil elemen pada posisi baris ke-1 dan kolom ke-4 dari array R

b = R[:,2]
print("Semua elemen pada kolom ke-3 adalah", b)
# Disini akan diambil elemen pada posisi kolom ke-3

c = R[1,:]
print("Semua elemen pada baris ke-2 adalah", c)
# Disini akan diambil semua elemen pada posisi baris ke-2

d = R[2,1:3]
print("Elemen pada baris ke-3 dan kolom ke-2 dan kolom ke-4 adalah", d)
# Disini akan diambil elemen pada baris ke-3 dan kolom ke-2 dan kolom ke-4

e = R[1,0:3:2]
# Ini artinya kita mengambil elemen di baris ke-2 dan kolom dari 1 sampai 4 dengan jarak sebesar 2
# Karena elemen di baris ke-2 adalah [1 3 7 6] dan kolom 1 sampai 4 pada baris ke-1 adalah [1 3 7 6] namun diambil 2 jarak dari kolom 1 sampai 4, maka
# Outputnya adalah [1 7]
print("Elemen pada baris ke-2 kolom ke-1 sampai kolom ke-4 dengan jarak 2 adalah", e)

print("\n")

# Akan mengubah elemen di baris dan kolom di index tertentu
R[0,3] = 205
# Ini berarti kita akan mengubah elemen di baris pertama dan kolom ke-4 menjadi 205
print("Hasil dari pengubahan elemen di baris pertama dan kolom ke-4 adalah")
print(R)

Elemen pada baris ke-1 dan kolom ke-4 di R adalah 1
Semua elemen pada kolom ke-3 adalah [5 7 5 5]
Semua elemen pada baris ke-2 adalah [1 3 7 6]
Elemen pada baris ke-3 dan kolom ke-2 dan kolom ke-4 adalah [8 5]
Elemen pada baris ke-2 kolom ke-1 sampai kolom ke-4 dengan jarak 2 adalah [1 7]


Hasil dari pengubahan elemen di baris pertama dan kolom ke-4 adalah
[[  2   4   5 205]
 [  1   3   7   6]
 [  6   8   5   3]
 [ 12   4   5   3]]


**5.20.3 Matrix pada Numpy**

In [47]:
# Membuat matriks menggunakan numpy

a = np.ones((2,3))
print(a)                # Disini dicetak matriks dengan jumlah baris 2 dan jumlah kolom 3 dimana seluruh elemennya 1

print("\n")
b = np.zeros((3,2))
print(b)              # Disini cetak matriks dengan jumlah baris 3 dan jumlah kolom 2 dimana seluruh elemennya 0

print("\n")
c = np.identity(2)    # Disini dicetak matriks identitas berordo 2x2 (baris sebanyak 2 dan kolom sebanyak 2)
print(c)

print("\n")
d = np.ones((2,2,3))  # Disini dicetak 2 matriks yang memiliki baris sebanyak 2 dan kolom sebanyak 3
print(d)

print("\n")
e = np.full((2,1),4)    # Disini dicetak matriks dengan 1 baris dan 2 kolom dengan seluruh elemennya adalah 4
print(e)

print("\n")
f = np.random.rand(4,3)
print(f)

print("\n")
g = np.random.randint(1,5,size=(2,3))
print(g)

[[1. 1. 1.]
 [1. 1. 1.]]


[[0. 0.]
 [0. 0.]
 [0. 0.]]


[[1. 0.]
 [0. 1.]]


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


[[4]
 [4]]


[[0.65011841 0.10149796 0.70922833]
 [0.58877963 0.41291252 0.31272418]
 [0.9706718  0.4279803  0.19245701]
 [0.57442855 0.94142429 0.00347858]]


[[3 4 2]
 [1 1 4]]


**5.20.4 Copy pada Numpy**

In [48]:
a = np.array([2,3,5,7,9])
print(a)

b = a
print(b)
# Disini hasilnya akan sama dengan perintah print(a) sebab b didefinisikan sama dengan a

b[0] = 10
print(b)
# Disini akan mengganti 1 yang terletak di posisi pertama dengan 10

print(a)
# Disini hasilnya akan sama dengan print(b) di atas karena b = a maka a = b

c = np.array([1,2,3,4,5])
print(c)

d = c.copy()
print(d)
# Disini hasilnya akan sama dengan print(c) di atas karena d mengcopy c

d[2] = 11
print(d)
# Disini akan mengganti 2 yang terletak diposisi ketiga dengan 11

print(c)
# Disini hasilnya tidak akan sama dengan print(d) karena d tidak didefinisikan sama dengan c, d hanya mengcopy c

[2 3 5 7 9]
[2 3 5 7 9]
[10  3  5  7  9]
[10  3  5  7  9]
[1 2 3 4 5]
[1 2 3 4 5]
[ 1  2 11  4  5]
[1 2 3 4 5]


**5.20.5 Operasi matematika pada Numpy**

In [49]:
# Mendefinisikan variabel dengan array
a = np.array([2,5,6,7])

x = a+2
print(x)
# Akan dijumlahkan setiap elemen nya dengan 2

y = a-3
print(y)
# Setiap elemen a akan dikurangkan dengan 3

z = a*6
print(z)
# Setiap elemen di a dikalikan dengan 6

k = a/4
print(k)
# Setiap elemen a akan dibagi dengan 4

l = a**2
print(l)
# Setiap elemen a akan dipangkatkan dengan 2

print("\n")

# Inisialisasi suatu variabel dengan array
b = np.array([0,1,2,3])
print(b)

m = a+b 
print(m)
# Disini akan dicetak matriks dengan elemennya adalah hasil penjumlahan dari a dengan b

n = a-b
print(n)
# Disini akan dicetak matriks dengan elemennya adalah hasil pengurangan dari a dengan b

o = a*b
print(o)
# Disini akan dicetak matriks dengan elemennya adalah hasil dari a kali b

print("\n")
p = np.cos(a)
print(p)

q = np.tan(a)
print(q)

r = np.sinh(a)
print(r)

s = np.cosh(b)
print(s)


[4 7 8 9]
[-1  2  3  4]
[12 30 36 42]
[0.5  1.25 1.5  1.75]
[ 4 25 36 49]


[0 1 2 3]
[ 2  6  8 10]
[2 4 4 4]
[ 0  5 12 21]


[-0.41614684  0.28366219  0.96017029  0.75390225]
[-2.18503986 -3.38051501 -0.29100619  0.87144798]
[  3.62686041  74.20321058 201.71315737 548.31612327]
[ 1.          1.54308063  3.76219569 10.067662  ]


**5.20.6 Perkalian Matrik pada Numpy**

In [50]:
# Mencetak matriks dengan numpy
a = np.array([[2,4,6,8],[1,2,3,4]])
print(a)

[[2 4 6 8]
 [1 2 3 4]]


In [51]:
# Mencetak matriks dengan numpy
s = np.array([[2,4,8],[1,2,3,4]])
print(s)
# Outputnya akan seperti dibawah ini karena jumlah ordo kedua matriks tidak sama

[list([2, 4, 8]) list([1, 2, 3, 4])]


<ipython-input-51-9a1ff2a6da4f>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  s = np.array([[2,4,8],[1,2,3,4]])


In [52]:
# Mencetak matriks dengan numpy
b = np.array([[1,2,3,4],[2,4,6,8]])
print(b)

[[1 2 3 4]
 [2 4 6 8]]


In [53]:
# Mengalikan matriks dengan numpy
c = a*b
print(c)

[[ 2  8 18 32]
 [ 2  8 18 32]]


In [54]:
d = np.matmul(a,b)
print(d)

ValueError: ignored

In [55]:
# Membagi matriks agar setiap matriks memiliki 2 elemen
e = np.array([[1,2],[3,4],[2,4],[6,8]])
print(e)

[[1 2]
 [3 4]
 [2 4]
 [6 8]]


In [56]:
f = np.matmul(a,e)
print(f)
# Hasilnya error karena ordo matriks a dan e berbeda

[[ 74 108]
 [ 37  54]]


In [57]:
g = a*e
print(g)

ValueError: ignored

**5.20.7 Min, max, dan sum pada Numpy**

In [58]:
# Mendefinisikan sebuah variabel dengan array
a = np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])
print(a)
# Mencetak matriks a dengan numpy

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [59]:
# Mencari nilai minimum dari matriks
b = np.min(a)
print(b)

1


In [60]:
c = np.min(a,axis=0)
print(c)

print("\n")

d = np.min(a,axis=1)
print(d)

[1 2 3 4]


[1 5 9]


In [61]:
# Mencari nilai max dari matriks
e = np.max(a)
print(e)

12


In [62]:
f = np.max(a,axis=0)
print(f)

print("\n")

g = np.max(a,axis=1)
print(g)

print("\n")

h = np.max(a,axis=3)
print(h)
# Output akan errror karena 3 diluar batas untuk dimensi 2

[ 9 10 11 12]


[ 4  8 12]




AxisError: ignored

In [63]:
# Menghitung jumlah dari matriks dengan numpy
i = np.sum(a)
print(i)

78


In [64]:
j = np.sum(a,axis=0)
print(j)

print("\n")

k = np.sum(a,axis=1)
print(k)

[15 18 21 24]


[10 26 42]
